// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/[locale]/blogs" | "/[locale]/blogs/[id]" | "/[locale]/clients" | "/[locale]/cookies-settings" | "/[locale]/news" | "/[locale]/news/[id]" | "/[locale]/privacy-policy" | "/[locale]/projects" | "/[locale]/projects/[id]" | "/[locale]/terms-of-service" | "/about" | "/careers" | "/careers/[id]" | "/careers/apply" | "/contact" | "/services" | "/services/[id]" | "/thank-you"
type PageRoutes = never
type LayoutRoutes = "/" | "/[locale]/blogs" | "/[locale]/news" | "/[locale]/projects"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/[locale]/blogs": { "locale": string; }
  "/[locale]/blogs/[id]": { "locale": string; "id": string; }
  "/[locale]/clients": { "locale": string; }
  "/[locale]/cookies-settings": { "locale": string; }
  "/[locale]/news": { "locale": string; }
  "/[locale]/news/[id]": { "locale": string; "id": string; }
  "/[locale]/privacy-policy": { "locale": string; }
  "/[locale]/projects": { "locale": string; }
  "/[locale]/projects/[id]": { "locale": string; "id": string; }
  "/[locale]/terms-of-service": { "locale": string; }
  "/about": {}
  "/careers": {}
  "/careers/[id]": { "id": string; }
  "/careers/apply": {}
  "/contact": {}
  "/services": {}
  "/services/[id]": { "id": string; }
  "/thank-you": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/[locale]/blogs": never
  "/[locale]/news": never
  "/[locale]/projects": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
